### ISSUE TITLE
Error when using default template

### ISSUE THREAD

**Issue by ghost** [Shadowv7/discord-reaction-role#4]
using ```
const manager = new ReactionRoleManager(client, {
    storage: "./reaction-role.json"
});
``` just returns ```
TypeError: `[object Object]` is not an Option Object
    at module.exports (/home/runner/NodeJSBotDiscord/node_modules/discord-reaction-role/node_modules/merge-options/index.js:164:10)
    at new ReactionRolesManager (/home/runner/NodeJSBotDiscord/node_modules/discord-reaction-role/src/Manager.js:18:20)
    at /home/runner/NodeJSBotDiscord/index.js:10:17
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)``` in console

**Comment by ghost** [comment]
Nvm, it was a repl.it problem
