### ISSUE TITLE
MessageID undefined

### ISSUE THREAD

**Issue by builtbygoose** [Shadowv7/discord-reaction-role#8]
I keep running into this issue any fixes?

```
(node:6428) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'messageID' of undefined
    at new ReactionRole (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\discord-reaction-role\src\ReactionRole.js:11:30)
    at Client.<anonymous> (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\discord-reaction-role\src\Manager.js:31:31)
    at Client.emit (events.js:376:20)
    at WebSocketShard.onMessage (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:295:27)
    at WebSocket.onMessage (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (events.js:376:20)
    at Receiver.dataMessage (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\bash\Desktop\Projects\LudumaDiscord\node_modules\ws\lib\receiver.js:367:17)
```

Looking into the reaction-role.json the MessageID is there.

**Comment by Legends-of-NGDB** [comment]
I have this error as well. Any solutions?
